### ISSUE TITLE
Provide url-args key by default even if this key is empty

### ISSUE THREAD

**Issue by IvanYukish** [kukosk/pyapns_client#5]
Hey, may you provide the default value for url-args? Because when I try to send notification to apns-server I get an error that url-args key isn't passed, although it must be passed even if key is empty.
<img width="1188" alt="Screenshot 2021-11-17 at 00 58 41" src="https://user-images.githubusercontent.com/44467358/142080027-ead0b913-f93f-4232-aedc-d6112e1ab7d0.png">
<img width="644" alt="Screenshot 2021-11-17 at 01 05 24" src="https://user-images.githubusercontent.com/44467358/142080604-f96c16a4-f3ec-463f-81c8-35db17dc9c33.png">

**Comment by kukosk** [comment]
Hey @IvanYukish and thank you very much for letting me know. It makes total sense, I didn't notice this value should always be present. I fixed it, did some other minor tweaks and published a new version 2.0.4 to pypi.
