### ISSUE TITLE
Would you consider adding support for proxies?

### ISSUE THREAD

**Issue by thierryba** [kukosk/pyapns_client#6]
http supports proxies. It would be easy enough to add support for this.
Thanks for considering this.

**Comment by kukosk** [comment]
Thanks for the feedback @thierryba!

While I totally see some users might want or need to use a proxy between their servers and APNS, I'm not sure if this would be used by many people and I'm not sure if I'll be able to find enough time to look into this rn :(. I'm totally open to merge it in if someone implements it though, would you be interested in trying it out and creating a PR?
